apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-sydvozwc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sydvozwc 
  name: go-sydvozwc
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-sydvozwc
    weight: 100 
