apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-sydvozwc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sydvozwc 
  name: go-sydvozwc
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-sydvozwc 
